### ISSUE TITLE
Releases for ROS iron, noetic, humble and rolling

### ISSUE THREAD

**Issue by Gonzalo-Mier** [shineyruan/ortools_ros#21]
Hi @shineyruan,

I'm using or-tools for a project that do releases for ROS and it's a nightmare to compile or-tools by source. I would like to ask you if you could create the releases for ROS, so everyone could access them.

You can use this guide from Steve Macenski:  https://gist.github.com/SteveMacenski/1c321d1c9edca096ae4d763d8327c2ee

Thank you and awesome work!

**Comment by shineyruan** [comment]
> Hi @shineyruan,
> 
> 
> 
> I'm using or-tools for a project that do releases for ROS and it's a nightmare to compile or-tools by source. I would like to ask you if you could create the releases for ROS, so everyone could access them.
> 
> 
> 
> You can use this guide from Steve Macenski:  https://gist.github.com/SteveMacenski/1c321d1c9edca096ae4d763d8327c2ee
> 
> 
> 
> Thank you and awesome work!

Hi @Gonzalo-Mier , 

Thank you for your suggestion! Unfortunately due to limited time and experience I was not able to create releases for ROS. However, I would love to help if anyone wants to take over and create releases for the ROS community.

**Comment by Gonzalo-Mier** [comment]
Thank you for your answer. I will do it then :)
